export enum RouteName {
  HomePage = "/",
  marketplace = "/marketplace",
  MarketplaceWithFilter = "/multi-collection-marketplace",
  StructuralLegaciesFilter = "/structural-legacies",
  SystemArchitectureFilter = "/system-architecture",
  HomeDesignFilter = "/home-designs",
  ProductsFilter = "/products",
  ClaimQubes = "/claimqubes",
  sell = "/sell",
  customToken = "/custom-token-marketplace",
  multipleCollection = "",
  marketplaceWithUrl = "/marketplace-with-url",
  multipleCurrencyMarketplace = "/multi-currency-marketplace",
  multipleCurrencySell = "/multi-currency-sell",
}
